#! /bin/bash

echo Configuring build for iphone device

rm Makefile
rm CMakeCache.txt
rm -rf CMakeFiles

unset CPATH
unset C_INCLUDE_PATH
unset CPLUS_INCLUDE_PATH
unset OBJC_INCLUDE_PATH
unset LIBS
unset DYLD_FALLBACK_LIBRARY_PATH
unset DYLD_FALLBACK_FRAMEWORK_PATH

OS_SIM="OS"
export SDKVER=`xcodebuild -showsdks | grep iphoneos | egrep "[[:digit:]]+\.[[:digit:]]+" -o | tail -1`
export DEVROOT=`xcode-select -p`/Platforms/iPhoneOS.platform/Developer
export XCODE_DEV_PATH=`xcode-select -p`
export SDKROOT="$DEVROOT/SDKs/iPhoneOS$SDKVER.sdk"
export PKG_CONFIG_PATH="$SDKROOT/usr/lib/pkgconfig":"/opt/iphone-$SDKVER/lib/pkgconfig":"/usr/local/iphone-$SDKVER/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="$PKG_CONFIG_PATH"
export MAINFOLDER=`pwd`

if [ $1 == iOS32 ]
then
  cmake -DCMAKE_TOOLCHAIN_FILE="./ios/iPhoneToolchains/iphone32.toolchain" -DCMAKE_INSTALL_PREFIX="/opt/iphone-$SDKVER" -DSDKVER=$SDKVER -DXCODE_DEV_PATH="$XCODE_DEV_PATH" -DMOBILE_CROSS=YES
else
  cmake -DCMAKE_TOOLCHAIN_FILE="./ios/iPhoneToolchains/iphone.toolchain" -DCMAKE_INSTALL_PREFIX="/opt/iphone-$SDKVER" -DSDKVER=$SDKVER -DXCODE_DEV_PATH="$XCODE_DEV_PATH" -DMOBILE_CROSS=YES
fi
